  
language: node_js
node_js:
   - "10"
branches:
   only:
      - master
script:
   - npm install
   - npm run build
deploy:
  local_dir: build
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET
  skip_cleanup: true
  on:
    branch: master